# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PuyoPuyo_Inae_Server' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PuyoPuyo_Inae_Server
pod 'Alamofire', '~> 5.2.2'
pod 'Kingfisher'
end
