# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOPT_27th_project_06' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SOPT_27th_project_06

pod 'Alamofire', '~> 5.2.2'

end
